spring.application.name=bank-api

# Habilita o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Garante uma URL fixa em memória para a conexão
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
